### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by sdomino**
This is a cool little library so I wanted to update the README to provide a working example for anyone who might need something like this.

### CODE REVIEW

**Comment by sdomino** [comment]
Any update on this by chance? Not that it really matters to me since I've got my implementation in place, but I'd love to help others out who stumble on this great project

**Comment by sdomino** [comment]
bump

**Comment by sdomino** [comment]
Any needed changes or feedback before this can be merged?

**Comment by rubentd** [comment]
Sorry for the enormous delay. And thanks for the contribution!

**Pull request merged**
